### ISSUE TITLE
Missing PyPI Release for languagePool Feature in ImageToTextTask, Breaking CAPTCHA Support

### ISSUE THREAD

**Issue by Sepera-okeq** [anti-captcha/anticaptcha-python#5]
A new parameter, language_pool, was added to the ImageToTextTask in this repository, but unfortunately, the library authors forgot to publish the updated version to PyPI. Without this parameter, solving certain CAPTCHAs (Russian ones), is not possible.

To make matters more challenging, the repository lacks standard setup files such as pyproject.toml, making it impossible to install the package directly from the repository as a workaround. Therefore, the only current solution is manually patching the library within virtual environment (venv).

**Comment by anti-captcha** [comment]
Hi, thanks for noting, fixed at PyPi.
